### ISSUE TITLE
BNB

### ISSUE THREAD

**Issue by Pearlminima** [binance/binance-api-swagger#11]
Before submitting a new issue, please check if a similar issue has already been filed.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version of binance-api-swagger
 - Tool name and version [e.g openapi-typescript version 4.4.0]

**Additional context**
Add any other context about the problem here![148683364-2f60a94c-40db-4f49-80e9-9678c7936a07.png](https://user-images.githubusercontent.com/45286747/155847443-e1f9f863-1e8b-499d-8c33-06548e11fdf9.png)

**Comment by aisling11** [comment]
Closing this issue as it doesn't seem to be directly related with binance-api-swagger.
