### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by Pearlminima** [binance/binance-api-swagger#12]
Nützliche Ressourcen
 Postboten-Sammlungen
 Eine Postboten-Sammlung, die die API-Endpunkte für eine schnelle und einfache Verwendung enthält.
 Dies wird neuen Benutzern empfohlen, die einen schnellen Einstieg in die Verwendung der API erhalten möchten.
 Verbinder
 Dies ist eine leichtgewichtige Bibliothek, die als Verbindung zur öffentlichen API von Binance fungiert.
 Python
 Node.js
 Rubin
 Punkt net
 Java
 Stolzieren
 Eine YAML-Datei mit OpenApi-Spezifikation für die RESTful-API steht zur Verfügung, ebenso wie eine Swagger-UI-Seite für die Beratung.
 Spot-Testnet
 Benutzer können das SPOT Testnet verwenden, um den SPOT-Handel zu üben.
 Derzeit ist dies nur über die API verfügbar.
 Es werden nur Endpunkte unterstützt, die mit /api/* beginnen, /sapi/* wird nicht unterstützt.
 Kontaktiere uns
 Binance-API-Telegrammgruppe
 Bei Fragen zu plötzlichem Leistungsabfall mit der API und/oder Websockets.
 Bei allgemeinen Fragen zur API, die nicht in der Dokumentation behandelt werden.
 Binance-Entwickler
 Für Fragen/Hilfe zur Codeimplementierung mit API und/oder Websockets.
 Binance-Kundensupport
 Für Fälle wie fehlende Mittel, Hilfe bei 2FA usw.

**Comment by aisling11** [comment]
Closing this issue as it doesn't seem to be directly related with binance-api-swagger.
