### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by uiii** [binance/binance-api-swagger#33]
Hello, no offence, but is this repo actively maintained? It looks outdated (last commit from 29 Aug) compared to https://binance-docs.github.io/apidocs/spot/en/#change-log. I am depending on this swagger api data in my code.

**Comment by 2pd** [comment]
Yeah, new change will be released soon.
Thanks for waiting.

**Comment by uiii** [comment]
great, thanks

**Comment by 2pd** [comment]
The swagger file is update to date.:)

**Comment by uiii** [comment]
thanks
