### ISSUE TITLE
Release fapi, dapi (and others) in swagger form

### ISSUE THREAD

**Issue by benine203** [binance/binance-api-swagger#55]
## question
is this being slated as TODO on your side?
alternatively, is it available anywhere else?

## side note
as a side note, this can be partially already done from the Postman definitions in the other repo using this pipeline:

For example for /dapi:

`curl https://raw.githubusercontent.com/binance/binance-api-postman/master/collections/Binance%20Coin-M%20Futures%20API.postman_collection.json | postman2openapi | openapi-typescript`

 - [postman2openapi](https://github.com/kevinswiber/postman2openapi)
 - [openapi-typescript](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-typescript)

the drawbacks here is that the conversion from postman to openapi is lossy as the type info as well as which parameters are optional are lost. Instead everything becomes `string`, but at least the field names and paths are preserved as well as the comments

**Comment by aisling-2** [comment]
Hello, the Futures (dapi or fapi) APIs are not part of this repository. They may become available in the long run, but there are limitations and different priorities at the moment, so it's not in the plan right now.
This being said, I'll close this issue, but with a "enhancement" tag. Thank you.

**Comment by benine203** [comment]
spot is arguably the least useful market of all of them
